/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as ApiConnectProviderRedirectRouteImport } from './routes/api.connect.$provider.redirect'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const ApiConnectProviderRedirectRoute =
  ApiConnectProviderRedirectRouteImport.update({
    id: '/api/connect/$provider/redirect',
    path: '/api/connect/$provider/redirect',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/api/connect/$provider/redirect': typeof ApiConnectProviderRedirectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/api/connect/$provider/redirect': typeof ApiConnectProviderRedirectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/connect/$provider/redirect': typeof ApiConnectProviderRedirectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/signin'
    | '/signup'
    | '/articles/$slug'
    | '/courses/$slug'
    | '/articles'
    | '/courses'
    | '/api/connect/$provider/redirect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/signin'
    | '/signup'
    | '/articles/$slug'
    | '/courses/$slug'
    | '/articles'
    | '/courses'
    | '/api/connect/$provider/redirect'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_auth'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/articles/$slug'
    | '/courses/$slug'
    | '/articles/'
    | '/courses/'
    | '/api/connect/$provider/redirect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRouteWithChildren
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiConnectProviderRedirectRoute: typeof ApiConnectProviderRedirectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/connect/$provider/redirect': {
      id: '/api/connect/$provider/redirect'
      path: '/api/connect/$provider/redirect'
      fullPath: '/api/connect/$provider/redirect'
      preLoaderRoute: typeof ApiConnectProviderRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRouteWithChildren,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiConnectProviderRedirectRoute: ApiConnectProviderRedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
